/**
 * 0.14.0 (§31 §4) pins: one icon module, one metaphor set. Every icon in the
 * app imports from src/shell/icons.tsx (semantic names over vendored
 * Framework7 glyphs, MIT); the Fluent icon package is gone entirely; and the
 * licensing rail holds — the repository ships NO Apple SF Symbols or SF font
 * assets (Apple-platform-only license; this bundle ships to Windows/Linux).
 *
 * Run: `node --test test/appleIcons.test.mjs`
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => readFileSync(path.join(ROOT, p), "utf8");
const sh = (cmd) => execSync(cmd + " || true", { cwd: ROOT, encoding: "utf8" }).trim();

test("no Fluent icon imports remain anywhere — the package itself is gone", () => {
  // The needle is concatenated so this file never matches its own pin.
  const needle = "@fluentui/" + "react-icons";
  const hits = sh(`grep -rla 'from "${needle}"' src/ app/ test/ scripts/ native/ --include=*.ts --include=*.tsx --include=*.mjs`);
  assert.equal(hits, "", `no file imports the Fluent icon package:\n${hits}`);
  const pkg = JSON.parse(read("package.json"));
  assert.ok(!(needle in (pkg.dependencies ?? {})), "direct dependency removed");
  // (The lockfile still resolves the package TRANSITIVELY — Fluent's own
  // components depend on it internally. The rail is OUR import surface.)
});

test("the registry is the single icon module: generated, attributed, semantic", () => {
  const icons = read("src/shell/icons.tsx");
  assert.match(icons, /GENERATED by scripts\/gen-glyphs\.mjs/);
  assert.match(icons, /Framework7 Icons v5 \(MIT/, "the attribution + license line");
  assert.match(icons, /NO Apple SF Symbols or SF fonts/, "the licensing rail is stated at the source");
  // The tab bar's active/rest pairs survive the swap.
  for (const name of ["IconChat", "IconChatFilled", "IconFolder", "IconFolderFilled", "IconSettings", "IconSettingsFilled"]) {
    assert.match(icons, new RegExp(`export const ${name} = makeIcon`), `${name} exists`);
  }
  // 1em + currentColor: existing font-size/color styling keeps working.
  assert.match(icons, /width="1em"/);
  assert.match(icons, /fill="currentColor"/);
});

test("license pin: the repo contains no SF font or SF Symbols asset files", () => {
  const fonts = sh(
    'find . -path ./node_modules -prune -o -type f \\( -iname "SF-*.otf" -o -iname "SF-*.ttf" -o -iname "*sf-pro*" -o -iname "*sfsymbols*" -o -iname "*.symbolset" \\) -print',
  );
  assert.equal(fonts, "", `no SF assets anywhere:\n${fonts}`);
});

test("the tab bar and controls ride the registry (spot pins)", () => {
  assert.match(read("src/shell/CompactTabBar.tsx"), /from "@\/shell\/icons"/);
  assert.match(read("src/shell/Sheet.tsx"), /IconClose/);
  assert.match(read("src/shell/controls/LhMenu.tsx"), /IconBack, IconChevronRight|IconChevronRight, IconBack/);
});

test("the generator is reproducible and validates the mapping (source pins)", () => {
  const gen = read("scripts/gen-glyphs.mjs");
  assert.match(gen, /Unresolvable glyphs/, "missing glyphs fail the run, never silently skip");
  assert.match(gen, /F7_SVG_DIR/, "regenerable without an install");
  assert.match(gen, /fill-rule/, "fill variants keep their winding rule");
});
