// Evidence-pack export (src/lib/evidencePack.ts + the exportChat wire shape).
// The composer is pure: one settled analytics answer in, ONE self-contained
// HTML document out — question, timestamp, provenance stamp, narrative +
// result table with its honesty footers verbatim, inline-SVG chart, the exact
// SQL, and the freshness/file provenance. These tests pin every section, the
// chart-fence removal, self-containment (no external URLs), determinism, and
// the exportChat wire shape.
import { test } from "node:test";
import assert from "node:assert/strict";
import { register } from "node:module";

register("./_ts-extensionless-hook.mjs", import.meta.url);

const { composeEvidencePack, answerMarkdownToHtml, provenanceStampText } =
  await import("../src/lib/evidencePack.ts");
const { formatSql } = await import("../src/lib/sqlFormat.ts");

// A realistic settled analytics answer: narrative (bold + citation), the
// result table, the deterministic "Query used" fence, freshness line, the
// truncation/coverage/row-cap honesty footers, and the chart fence.
const SQL =
  "SELECT region, SUM(amount) AS total FROM sales GROUP BY region ORDER BY total DESC";
const CHART_JSON =
  '{"kind":"bar","x":["Northeast","Northwest"],"series":[{"name":"total","values":[4120,2200]}]}';
const CONTENT = [
  "The **Northeast** region leads with **$4,120** in total sales. [1]",
  "",
  "| region | total |",
  "| --- | --- |",
  "| Northeast | 4120 |",
  "| Northwest | 2200 |",
  "",
  "*Query used:*",
  "```sql",
  SQL,
  "```",
  "*Computed from:* “sales.csv” (saved 2 hours ago)",
  "_Showing the first 200 of 12,431 rows._",
  "_Analyzed 1 of 2 in-scope tabular files (engine table limit)._",
  "_“sales.csv” analyzed to its first 5,000 rows (workbook row cap)._",
  "",
  "```lighthouse-chart",
  CHART_JSON,
  "```",
  "",
].join("\n");

const CHART_SVG =
  '<svg xmlns="http://www.w3.org/2000/svg" width="520" height="220" viewBox="0 0 520 220" role="img">' +
  '<rect x="0" y="0" width="520" height="220" fill="#ffffff"></rect>' +
  '<text x="10" y="20" fill="#1a1a1a">total by region</text></svg>';

const INPUT = {
  question: "Revenue by region?",
  contentMarkdown: CONTENT,
  chartSvg: CHART_SVG,
  meta: { origin: "anthropic", excerptCount: 3, sourceFileCount: 2 },
  analytics: { sql: SQL, fileIds: ["finance/sales.csv"] },
  references: [{ fileId: "finance/sales.csv", name: "sales.csv" }],
  generatedAt: Date.UTC(2026, 6, 15, 9, 30),
};

test("the pack contains every section", () => {
  const html = composeEvidencePack(INPUT);

  // (a) question (title + h1), timestamp, provenance stamp line.
  assert.ok(html.includes("<title>Revenue by region?</title>"));
  assert.ok(html.includes("<h1>Revenue by region?</h1>"));
  assert.ok(html.includes("2026-07-15 09:30 UTC"));
  assert.ok(html.includes("Answered via Anthropic Claude — 3 excerpts from 2 files sent"));

  // (b) narrative + the result table.
  assert.ok(html.includes("<strong>Northeast</strong>"));
  assert.ok(html.includes("<strong>$4,120</strong>"));
  assert.ok(html.includes("<th>region</th>"));
  assert.ok(html.includes("<td>Northeast</td>"));
  assert.ok(html.includes("<td>4120</td>"));

  // The honesty footers ride along VERBATIM.
  assert.ok(html.includes("Showing the first 200 of 12,431 rows."));
  assert.ok(html.includes("Analyzed 1 of 2 in-scope tabular files (engine table limit)."));
  assert.ok(html.includes("analyzed to its first 5,000 rows (workbook row cap)."));

  // (c) the chart as inline SVG.
  assert.ok(html.includes("<svg"));
  assert.ok(html.includes("total by region"));

  // (d) the exact SQL.
  assert.ok(html.includes("SELECT region, SUM(amount) AS total FROM sales"));

  // (e) provenance: freshness line verbatim + the files read.
  assert.ok(html.includes("Computed from:"));
  assert.ok(html.includes("“sales.csv” (saved 2 hours ago)"));
  assert.ok(html.includes("sales.csv — finance/sales.csv"));

  // (f) footer.
  assert.ok(
    html.includes(
      "Generated by Lighthouse · 2026-07-15 09:30 UTC · every number computed by the engine from your files",
    ),
  );
});

test("the chart fence never appears raw — the chart travels only as SVG", () => {
  const html = composeEvidencePack(INPUT);
  assert.ok(!html.includes("lighthouse-chart"));
  assert.ok(!html.includes('"kind":"bar"'));
  // …and without a captured SVG the chart section is omitted cleanly.
  const noChart = composeEvidencePack({ ...INPUT, chartSvg: undefined });
  assert.ok(!noChart.includes("<svg"));
  assert.ok(!noChart.includes(">Chart<"));
  // Everything else still stands.
  assert.ok(noChart.includes("<td>Northeast</td>"));
});

test("self-contained: no external URLs anywhere in the document", () => {
  const html = composeEvidencePack(INPUT);
  // The SVG xmlns is a namespace IDENTIFIER, not a fetched resource — strip
  // namespace declarations, then nothing http(s) may remain.
  const withoutXmlns = html.replace(/xmlns(:[a-z]+)?="[^"]*"/g, "");
  assert.equal(withoutXmlns.match(/https?:\/\//), null);
  // And nothing executable or remote-loading is emitted by the composer.
  assert.ok(!html.includes("<script"));
  assert.ok(!html.includes("<link"));
});

test("deterministic: fixed inputs produce byte-identical output", () => {
  assert.equal(composeEvidencePack(INPUT), composeEvidencePack(INPUT));
});

test("questions and cells are HTML-escaped, never interpreted", () => {
  const html = composeEvidencePack({
    ...INPUT,
    question: 'Totals for <script>"Q3 & Q4"</script>?',
  });
  assert.ok(!html.includes('<script>"Q3'));
  assert.ok(html.includes("&lt;script&gt;&quot;Q3 &amp; Q4&quot;&lt;/script&gt;?"));
});

test("provenance stamp wording matches the on-screen stamp exactly", () => {
  assert.equal(
    provenanceStampText({ origin: "device", excerptCount: 0, sourceFileCount: 0 }),
    "Answered on this device",
  );
  assert.equal(
    provenanceStampText({ origin: "anthropic", excerptCount: 1, sourceFileCount: 1 }),
    "Answered via Anthropic Claude — 1 excerpt from 1 file sent",
  );
  // Unknown provider ids fall back to the id — never a fabricated vendor.
  assert.equal(
    provenanceStampText({ origin: "acme", excerptCount: 2, sourceFileCount: 1 }),
    "Answered via acme — 2 excerpts from 1 file sent",
  );
  // A device-origin pack renders the same line the chat shows.
  const html = composeEvidencePack({
    ...INPUT,
    meta: { origin: "device", excerptCount: 0, sourceFileCount: 0 },
  });
  assert.ok(html.includes("Answered on this device"));
});

test("answerMarkdownToHtml renders the engine's subset deterministically", () => {
  // The sql fence keeps its content escaped inside a <pre>.
  const sqlHtml = answerMarkdownToHtml('```sql\nSELECT * FROM "t" WHERE a < 2\n```');
  assert.ok(sqlHtml.includes("<pre><code>SELECT * FROM &quot;t&quot; WHERE a &lt; 2</code></pre>"));
  // A literal `*` inside a code span never opens emphasis.
  const inline = answerMarkdownToHtml("Run `SELECT * FROM t` twice * not emphasis");
  assert.ok(inline.includes("<code>SELECT * FROM t</code>"));
  assert.ok(!inline.includes("<em>"));
  // Citation markers stay plain text (they map to the numbered file list).
  assert.ok(answerMarkdownToHtml("Total is 42. [1]").includes("Total is 42. [1]"));
  // Underscore emphasis fires only free-standing — snake_case survives.
  const snake = answerMarkdownToHtml("| a_col | b_col |\n| --- | --- |\n| x_1 | y_2 |");
  assert.ok(snake.includes("<th>a_col</th>"));
  assert.ok(snake.includes("<td>x_1</td>"));
});

// --- Recipe answers (openspec: add-recipes §3.2) ------------------------------
//
// §3.2 FINDING (verified, no new pack section): a recipe answer's
// `*Queries used (N):*` footer lists EVERY executed query as its own ```sql
// fence, and the §1 `*Assumptions:*` ledger rides right beside it — BOTH in the
// answer text (m.content, which the engine caches verbatim). composeEvidencePack
// renders m.content in section (b) via answerMarkdownToHtml, which turns each
// ```sql fence into a <pre><code> block. So a recipe pack already carries the
// whole plan + the ledger with NO dedicated "Plan" section — the verbatim footer
// is sufficient. These pins prove the spec scenario: "an evidence pack of a
// recipe answer that ran four queries → the pack lists all four queries and the
// result, and renders offline."

const RQ1 = "SELECT SUM(amount) AS total FROM sales WHERE month = '2026-06'";
const RQ2 = "SELECT SUM(amount) AS total FROM sales WHERE month = '2026-05'";
const RQ3 = "SELECT SUM(amount) - LAG(SUM(amount)) AS delta FROM sales GROUP BY month";
const RQ4 = "SELECT COUNT(DISTINCT region) AS groups FROM sales";
// The extractive shape: result tables + the multi-step footer + the §1 ledger,
// no prose (narration is skippable) — exactly what synth.rs emits on the
// no-model path, and what the answer_cache stores verbatim.
const RECIPE_CONTENT = [
  "**Current period total**",
  "",
  "| total |",
  "| --- |",
  "| 4120 |",
  "",
  "**Prior period total**",
  "",
  "| total |",
  "| --- |",
  "| 3300 |",
  "",
  "*Queries used (4):*",
  "1.",
  "```sql",
  RQ1,
  "```",
  "2.",
  "```sql",
  RQ2,
  "```",
  "3.",
  "```sql",
  RQ3,
  "```",
  "4.",
  "```sql",
  RQ4,
  "```",
  "*Computed from:* “sales.csv” (saved 2 hours ago)",
  "*Assumptions:*",
  "- Date column: month (period = calendar month)",
  "- Metric: SUM(amount) — null cells skipped",
  "- Considered 12,431 rows",
  "",
].join("\n");

test("evidence pack of a recipe answer lists ALL four queries + the ledger, offline", () => {
  const html = composeEvidencePack({
    question: "run-recipe:variance-vs-last-period on sales.csv",
    contentMarkdown: RECIPE_CONTENT,
    // The representative query rides AnalyticsMeta (pins keep working); the
    // FULL plan rides section (b) via the footer, which is what we assert here.
    analytics: { sql: RQ1, fileIds: ["finance/sales.csv"] },
    references: [{ fileId: "finance/sales.csv", name: "sales.csv" }],
    generatedAt: Date.UTC(2026, 6, 15, 9, 30),
  });

  // The whole plan: every executed query renders as its own <pre><code> block
  // (section b's verbatim footer — no dedicated Plan section needed).
  for (const sql of [RQ1, RQ2, RQ3, RQ4]) {
    assert.ok(html.includes(`<pre><code>${sql}</code></pre>`), `the pack lists ${sql}`);
  }
  // The results render (the recipe's result tables).
  assert.ok(html.includes("<td>4120</td>"));
  assert.ok(html.includes("<td>3300</td>"));
  // The §1 assumption ledger rides flat in section (b) — engine-derived facts.
  assert.ok(html.includes("Date column: month (period = calendar month)"));
  assert.ok(html.includes("null cells skipped"));
  assert.ok(html.includes("Considered 12,431 rows"));
  // Renders offline: no external resource of any kind (the pack invariant).
  const withoutXmlns = html.replace(/xmlns(:[a-z]+)?="[^"]*"/g, "");
  assert.equal(withoutXmlns.match(/https?:\/\//), null);
  assert.ok(!html.includes("<script"));
  assert.ok(!html.includes("<link"));
});


const BOARD_SQL_LIVE =
  "SELECT region, SUM(amount) AS total FROM sales GROUP BY region ORDER BY total DESC";
const BOARD_SQL_STORED = "SELECT COUNT(*) AS orders FROM orders";

// --- Wire shape: the pack rides the EXISTING exportChat op -------------------

test("exportChat wire: the pack asks for html; the artifact comes BACK", async () => {
  const calls = [];
  const realFetch = globalThis.fetch;
  globalThis.fetch = async (url, init) => {
    calls.push({ url, init });
    return {
      ok: true,
      status: 200,
      json: async () => ({ savedName: "x.html", content: "<!doctype html>…" }),
    };
  };
  try {
    const { ragService } = await import("../src/contracts/real/rag.real.ts");
    // The evidence-pack call: html. 0.15.0 — the engine writes nothing and
    // hands the artifact back for the OS save dialog, so there is no savedId
    // and no `subdir` (the vault folders it named are gone).
    const res = await ragService.exportChat("Revenue by region?", "<!doctype html>…", {
      ext: "html",
    });
    assert.equal(res.savedName, "x.html");
    assert.equal(res.content, "<!doctype html>…");
    assert.equal(res.savedId, undefined, "nothing was written, so there is no id");
    assert.equal(calls[0].url, "/api/rag");
    assert.deepEqual(JSON.parse(calls[0].init.body), {
      op: "exportChat",
      title: "Revenue by region?",
      markdown: "<!doctype html>…",
      ext: "html",
    });
    // The plain chat export sends NO ext key — the engine's "md" default.
    await ragService.exportChat("Team sync", "# transcript");
    assert.deepEqual(JSON.parse(calls[1].init.body), {
      op: "exportChat",
      title: "Team sync",
      markdown: "# transcript",
    });
  } finally {
    globalThis.fetch = realFetch;
  }
});
