// Evidence-pack export (src/lib/evidencePack.ts + the exportChat wire shape).
// The composer is pure: one settled analytics answer in, ONE self-contained
// HTML document out — question, timestamp, provenance stamp, narrative +
// result table with its honesty footers verbatim, inline-SVG chart, the exact
// SQL, and the freshness/file provenance. These tests pin every section, the
// chart-fence removal, self-containment (no external URLs), determinism, and
// the extended-but-backward-compatible exportChat wire shape.
import { test } from "node:test";
import assert from "node:assert/strict";
import { register } from "node:module";

register("./_ts-extensionless-hook.mjs", import.meta.url);

const { composeEvidencePack, composeBoardPack, answerMarkdownToHtml, provenanceStampText } =
  await import("../src/lib/evidencePack.ts");

// A realistic settled analytics answer: narrative (bold + citation), the
// result table, the deterministic "Query used" fence, freshness line, the
// truncation/coverage/row-cap honesty footers, and the chart fence.
const SQL =
  "SELECT region, SUM(amount) AS total FROM sales GROUP BY region ORDER BY total DESC";
const CHART_JSON =
  '{"kind":"bar","x":["Northeast","Northwest"],"series":[{"name":"total","values":[4120,2200]}]}';
const CONTENT = [
  "The **Northeast** region leads with **$4,120** in total sales. [1]",
  "",
  "| region | total |",
  "| --- | --- |",
  "| Northeast | 4120 |",
  "| Northwest | 2200 |",
  "",
  "*Query used:*",
  "```sql",
  SQL,
  "```",
  "*Computed from:* “sales.csv” (saved 2 hours ago)",
  "_Showing the first 200 of 12,431 rows._",
  "_Analyzed 1 of 2 in-scope tabular files (engine table limit)._",
  "_“sales.csv” analyzed to its first 5,000 rows (workbook row cap)._",
  "",
  "```lighthouse-chart",
  CHART_JSON,
  "```",
  "",
].join("\n");

const CHART_SVG =
  '<svg xmlns="http://www.w3.org/2000/svg" width="520" height="220" viewBox="0 0 520 220" role="img">' +
  '<rect x="0" y="0" width="520" height="220" fill="#ffffff"></rect>' +
  '<text x="10" y="20" fill="#1a1a1a">total by region</text></svg>';

const INPUT = {
  question: "Revenue by region?",
  contentMarkdown: CONTENT,
  chartSvg: CHART_SVG,
  meta: { origin: "anthropic", excerptCount: 3, sourceFileCount: 2 },
  analytics: { sql: SQL, fileIds: ["finance/sales.csv"] },
  references: [{ fileId: "finance/sales.csv", name: "sales.csv" }],
  generatedAt: Date.UTC(2026, 6, 15, 9, 30),
};

test("the pack contains every section", () => {
  const html = composeEvidencePack(INPUT);

  // (a) question (title + h1), timestamp, provenance stamp line.
  assert.ok(html.includes("<title>Revenue by region?</title>"));
  assert.ok(html.includes("<h1>Revenue by region?</h1>"));
  assert.ok(html.includes("2026-07-15 09:30 UTC"));
  assert.ok(html.includes("Answered via Anthropic Claude — 3 excerpts from 2 files sent"));

  // (b) narrative + the result table.
  assert.ok(html.includes("<strong>Northeast</strong>"));
  assert.ok(html.includes("<strong>$4,120</strong>"));
  assert.ok(html.includes("<th>region</th>"));
  assert.ok(html.includes("<td>Northeast</td>"));
  assert.ok(html.includes("<td>4120</td>"));

  // The honesty footers ride along VERBATIM.
  assert.ok(html.includes("Showing the first 200 of 12,431 rows."));
  assert.ok(html.includes("Analyzed 1 of 2 in-scope tabular files (engine table limit)."));
  assert.ok(html.includes("analyzed to its first 5,000 rows (workbook row cap)."));

  // (c) the chart as inline SVG.
  assert.ok(html.includes("<svg"));
  assert.ok(html.includes("total by region"));

  // (d) the exact SQL.
  assert.ok(html.includes("SELECT region, SUM(amount) AS total FROM sales"));

  // (e) provenance: freshness line verbatim + the files read.
  assert.ok(html.includes("Computed from:"));
  assert.ok(html.includes("“sales.csv” (saved 2 hours ago)"));
  assert.ok(html.includes("sales.csv — finance/sales.csv"));

  // (f) footer.
  assert.ok(
    html.includes(
      "Generated by Lighthouse · 2026-07-15 09:30 UTC · every number computed by the engine from your files",
    ),
  );
});

test("the chart fence never appears raw — the chart travels only as SVG", () => {
  const html = composeEvidencePack(INPUT);
  assert.ok(!html.includes("lighthouse-chart"));
  assert.ok(!html.includes('"kind":"bar"'));
  // …and without a captured SVG the chart section is omitted cleanly.
  const noChart = composeEvidencePack({ ...INPUT, chartSvg: undefined });
  assert.ok(!noChart.includes("<svg"));
  assert.ok(!noChart.includes(">Chart<"));
  // Everything else still stands.
  assert.ok(noChart.includes("<td>Northeast</td>"));
});

test("self-contained: no external URLs anywhere in the document", () => {
  const html = composeEvidencePack(INPUT);
  // The SVG xmlns is a namespace IDENTIFIER, not a fetched resource — strip
  // namespace declarations, then nothing http(s) may remain.
  const withoutXmlns = html.replace(/xmlns(:[a-z]+)?="[^"]*"/g, "");
  assert.equal(withoutXmlns.match(/https?:\/\//), null);
  // And nothing executable or remote-loading is emitted by the composer.
  assert.ok(!html.includes("<script"));
  assert.ok(!html.includes("<link"));
});

test("deterministic: fixed inputs produce byte-identical output", () => {
  assert.equal(composeEvidencePack(INPUT), composeEvidencePack(INPUT));
});

test("questions and cells are HTML-escaped, never interpreted", () => {
  const html = composeEvidencePack({
    ...INPUT,
    question: 'Totals for <script>"Q3 & Q4"</script>?',
  });
  assert.ok(!html.includes('<script>"Q3'));
  assert.ok(html.includes("&lt;script&gt;&quot;Q3 &amp; Q4&quot;&lt;/script&gt;?"));
});

test("provenance stamp wording matches the on-screen stamp exactly", () => {
  assert.equal(
    provenanceStampText({ origin: "device", excerptCount: 0, sourceFileCount: 0 }),
    "Answered on this device",
  );
  assert.equal(
    provenanceStampText({ origin: "anthropic", excerptCount: 1, sourceFileCount: 1 }),
    "Answered via Anthropic Claude — 1 excerpt from 1 file sent",
  );
  // Unknown provider ids fall back to the id — never a fabricated vendor.
  assert.equal(
    provenanceStampText({ origin: "acme", excerptCount: 2, sourceFileCount: 1 }),
    "Answered via acme — 2 excerpts from 1 file sent",
  );
  // A device-origin pack renders the same line the chat shows.
  const html = composeEvidencePack({
    ...INPUT,
    meta: { origin: "device", excerptCount: 0, sourceFileCount: 0 },
  });
  assert.ok(html.includes("Answered on this device"));
});

test("answerMarkdownToHtml renders the engine's subset deterministically", () => {
  // The sql fence keeps its content escaped inside a <pre>.
  const sqlHtml = answerMarkdownToHtml('```sql\nSELECT * FROM "t" WHERE a < 2\n```');
  assert.ok(sqlHtml.includes("<pre><code>SELECT * FROM &quot;t&quot; WHERE a &lt; 2</code></pre>"));
  // A literal `*` inside a code span never opens emphasis.
  const inline = answerMarkdownToHtml("Run `SELECT * FROM t` twice * not emphasis");
  assert.ok(inline.includes("<code>SELECT * FROM t</code>"));
  assert.ok(!inline.includes("<em>"));
  // Citation markers stay plain text (they map to the numbered file list).
  assert.ok(answerMarkdownToHtml("Total is 42. [1]").includes("Total is 42. [1]"));
  // Underscore emphasis fires only free-standing — snake_case survives.
  const snake = answerMarkdownToHtml("| a_col | b_col |\n| --- | --- |\n| x_1 | y_2 |");
  assert.ok(snake.includes("<th>a_col</th>"));
  assert.ok(snake.includes("<td>x_1</td>"));
});

// --- Board pack (openspec: add-boards §5.1) -----------------------------------
//
// composeBoardPack composes a whole board the same way: title + per-card
// sections (question heading, rendered table, inline-SVG chart, freshness
// stamp, stale note) + ONE "Queries" appendix (every card's SQL + engine
// footer verbatim). Two representative cards: a LIVE chart+table card (the
// desktop engine's re-execution) and a STORED summary card (the twin's
// last-known snapshot, labeled stored exactly as on screen).

const BOARD_SQL_LIVE =
  "SELECT region, SUM(amount) AS total FROM sales GROUP BY region ORDER BY total DESC";
const BOARD_SQL_STORED = "SELECT COUNT(*) AS orders FROM orders";
const BOARD_INPUT = {
  title: "My board",
  generatedAt: Date.UTC(2026, 6, 15, 9, 30),
  cards: [
    {
      question: "Revenue by region?",
      markdown: [
        "| region | total |",
        "| --- | --- |",
        "| Northeast | 4120 |",
        "| Northwest | 2200 |",
      ].join("\n"),
      chartSvg: CHART_SVG,
      freshness: "Computed from: “sales.csv” (saved 2 hours ago)",
      sql: BOARD_SQL_LIVE,
      footer:
        "*Computed from:* “sales.csv” (saved 2 hours ago)\n_Showing the first 3 of 8 rows._",
      live: true,
    },
    {
      question: "How many orders shipped?",
      markdown: "orders 1,204",
      freshness: "stored · checked 3h ago",
      sql: BOARD_SQL_STORED,
      live: false,
    },
  ],
};

test("board pack: both card sections, freshness stamps, inline SVG, ONE Queries appendix", () => {
  const html = composeBoardPack(BOARD_INPUT);

  // Title + generation stamp.
  assert.ok(html.includes("<title>My board</title>"));
  assert.ok(html.includes("<h1>My board</h1>"));
  assert.ok(html.includes("Generated 2026-07-15 09:30 UTC"));

  // Per-card sections, the question as heading, in board order.
  const live = html.indexOf("<h2>Revenue by region?</h2>");
  const stored = html.indexOf("<h2>How many orders shipped?</h2>");
  assert.ok(live !== -1 && stored !== -1 && live < stored);

  // The live card's row-capped table renders as real HTML…
  assert.ok(html.includes("<th>region</th>"));
  assert.ok(html.includes("<td>Northeast</td>"));
  assert.ok(html.includes("<td>4120</td>"));
  // …with its captured chart inline as SVG.
  assert.ok(html.includes("<svg"));
  assert.ok(html.includes("total by region"));

  // The stored card's body is its summary TEXT, and its freshness stamp
  // keeps the on-screen "stored" labeling — never passed off as live.
  assert.ok(html.includes("orders 1,204"));
  assert.ok(html.includes("Computed from: “sales.csv” (saved 2 hours ago)"));
  assert.ok(html.includes("stored · checked 3h ago"));

  // Exactly ONE Queries appendix, at the end, listing every card's SQL…
  assert.equal(html.match(/>Queries</g).length, 1);
  const appendix = html.indexOf(">Queries<");
  assert.ok(appendix > stored);
  assert.ok(html.indexOf(BOARD_SQL_LIVE) > appendix);
  assert.ok(html.indexOf(BOARD_SQL_STORED) > appendix);
  // …the live card's engine footer verbatim (emphasis marks are syntax)…
  assert.ok(html.includes("Showing the first 3 of 8 rows."));
  // …and the stored card's entry repeats its stored stamp in place of a
  // footer (nothing ran, so nothing may read as engine provenance): the
  // stored line appears twice — card section + appendix.
  assert.equal(html.match(/stored · checked 3h ago/g).length, 2);

  // The footer's promise stands.
  assert.ok(
    html.includes(
      "Generated by Lighthouse · 2026-07-15 09:30 UTC · every number computed by the engine from your files",
    ),
  );
});

test("board pack: a failed card carries its stale note, danger-inked, body omitted", () => {
  const html = composeBoardPack({
    title: "My board",
    generatedAt: Date.UTC(2026, 6, 15, 9, 30),
    cards: [
      {
        question: "Broken pin?",
        freshness: "checked just now",
        sql: "SELECT 1",
        live: true,
        staleNote: "stale: watched file missing: sales.csv",
      },
    ],
  });
  assert.ok(html.includes('<p class="stale">stale: watched file missing: sales.csv</p>'));
  // The freshness line is kept — the pins-dialog honesty posture.
  assert.ok(html.includes("checked just now"));
  // And the appendix still lists the query.
  assert.ok(html.includes("SELECT 1"));
});

test("board pack: self-contained — no external URLs, scripts, or links", () => {
  const html = composeBoardPack(BOARD_INPUT);
  // Same invariant as the evidence pack: xmlns is a namespace identifier,
  // not a fetched resource — strip declarations, then nothing http(s) remains.
  const withoutXmlns = html.replace(/xmlns(:[a-z]+)?="[^"]*"/g, "");
  assert.equal(withoutXmlns.match(/https?:\/\//), null);
  assert.ok(!html.includes("<script"));
  assert.ok(!html.includes("<link"));
});

test("board pack: an empty board exports honestly — minimal, no appendix", () => {
  const html = composeBoardPack({
    title: "My board",
    generatedAt: Date.UTC(2026, 6, 15, 9, 30),
    cards: [],
  });
  assert.ok(html.includes("<h1>My board</h1>"));
  assert.ok(html.includes("This board has no cards."));
  assert.ok(!html.includes(">Queries<"));
  assert.ok(!html.includes("<svg"));
  assert.ok(
    html.includes(
      "Generated by Lighthouse · 2026-07-15 09:30 UTC · every number computed by the engine from your files",
    ),
  );
});

test("board pack: deterministic bytes; questions and notes escaped, never interpreted", () => {
  assert.equal(composeBoardPack(BOARD_INPUT), composeBoardPack(BOARD_INPUT));
  const html = composeBoardPack({
    ...BOARD_INPUT,
    cards: [
      {
        ...BOARD_INPUT.cards[1],
        question: 'Orders <script>"Q3 & Q4"</script>?',
        staleNote: 'error: <img src="https://evil.example/x.png">',
      },
    ],
  });
  assert.ok(!html.includes('<script>"Q3'));
  assert.ok(html.includes("Orders &lt;script&gt;&quot;Q3 &amp; Q4&quot;&lt;/script&gt;?"));
  // An error string can't smuggle markup (or a remote fetch) into the pack.
  assert.ok(!html.includes("<img"));
});

// --- Wire shape: the pack rides the EXISTING exportChat op -------------------

test("exportChat wire: pack adds subdir/ext; the default shape is untouched", async () => {
  const calls = [];
  const realFetch = globalThis.fetch;
  globalThis.fetch = async (url, init) => {
    calls.push({ url, init });
    return {
      ok: true,
      status: 200,
      json: async () => ({ savedId: "Lighthouse Results/x.html", savedName: "x.html" }),
    };
  };
  try {
    const { ragService } = await import("../src/contracts/real/rag.real.ts");
    // The evidence-pack call: html into Lighthouse Results.
    const res = await ragService.exportChat("Revenue by region?", "<!doctype html>…", {
      subdir: "Lighthouse Results",
      ext: "html",
    });
    assert.equal(res.savedId, "Lighthouse Results/x.html");
    assert.equal(calls[0].url, "/api/rag");
    assert.deepEqual(JSON.parse(calls[0].init.body), {
      op: "exportChat",
      title: "Revenue by region?",
      markdown: "<!doctype html>…",
      subdir: "Lighthouse Results",
      ext: "html",
    });
    // Backward behavior: the plain chat export sends NO subdir/ext keys.
    await ragService.exportChat("Team sync", "# transcript");
    assert.deepEqual(JSON.parse(calls[1].init.body), {
      op: "exportChat",
      title: "Team sync",
      markdown: "# transcript",
    });
  } finally {
    globalThis.fetch = realFetch;
  }
});
